### ISSUE TITLE
An error occurred when deploying production

### ISSUE THREAD

**Issue by ngyngcphu** [phucvinh57/fastify-template#50]
Hello @phucvinh57 !
I noticed an error appearing in the last line in the `Dockerfile`: 
```sh
CMD yarn db:deploy && node index.js
```
I have fixed it like this, and deployed to VPS successfully:
```sh
CMD yarn db:deploy && node src/index.js
```
Sorry, I found this error in TickFlow project, but just now reported it to you.
Please consider this issue !

**Comment by phucvinh57** [comment]
Fixed in #51
